### ISSUE TITLE
Extension for constraint satisfaction problems (no objective function)

### ISSUE THREAD

**Issue by kostis-init** [skadio/ner4opt#4]
Hello! Is it possible to extend the framework in such a way that we could use it for problems that do not contain an objective function (such as logic grid puzzles)? Currently, an exception is thrown when trying to run the method for such an example. Here is a sample run and exception log:

```
from ner4opt import Ner4Opt

problem_description = '''
You are provided with information about four clients, their chosen masseuses, and the price they paid for their services. Your task is to match each client with their masseuse and the amount they paid based on the following clues:

1. Hannah paid more than the client of Teri.
2. Freda paid $20 more than Lynda's client.
3. Hannah paid $10 less than Nancy's client.
4. Nancy's client, Hannah, and Ginger patronized different masseuses.
5. Hannah either paid $180 or was Lynda's client.

Clients: Aimee, Ginger, Freda, Hannah  
Prices: $150, $160, $170, $180  
Masseuses: Lynda, Nancy, Teri, Whitney

Based on the clues provided, determine which client paid how much and which masseuse they chose.
'''
ner4opt = Ner4Opt(model="hybrid")
ner4opt.get_entities(problem_description)
```

```
    ner4opt.get_entities(problem_description)
  File ".../python3.9/site-packages/ner4opt/ner4opt.py", line 166, in get_entities
    features = featurizer.get_features()
  File ".../python3.9/site-packages/ner4opt/featurizer.py", line 585, in get_features
    obj_dir_gazetteer_features[token_index],
IndexError: list index out of range
```

Thank you!

**Comment by skadio** [comment]
Thank you for submitting! @kuppulur  let's chat about this

**Comment by skadio** [comment]
Fix on the way https://github.com/skadio/ner4opt/pull/5

**Comment by kuppulur** [comment]
@kostis-init Thanks for bringing this to our attention.

Upon investigation, we've determined that the problem was not caused by a lack of an objective function. Instead, it stemmed from the presence of newline characters (e.g., "\n", "\r") and multiple spaces within the text, which our models were not originally designed to handle effectively.

To address this, we've implemented a new preprocessing routine specifically aimed at removing these types of characters to ensure cleaner and more consistent input data. This enhancement has already shown positive results, as demonstrated in the attached screenshot where we successfully extracted entities from the text you shared. The screenshot is from our huggingface spaces demo.
![ner4opt_spaces](https://github.com/skadio/ner4opt/assets/3698879/7881a9d3-8382-4cbe-b1e0-a5b86c2353c6)

Also, our models are not trained on the kind of examples you shared above. Consequently, it's unlikely that they would perform optimally without some adjustments. We encourage you to explore our training notebooks, which could guide you in adapting the models to better suit your unique dataset.

If you encounter any further issues or have additional questions, please don't hesitate to reach out. Your engagement with our library is highly valued. Thank you again for your interest and for helping us improve our library.

**Comment by skadio** [comment]
Just judging from that one example, it is doing a pretty good job identifying params and vars  (even thought this text is different than nl4opt competition data)

**Comment by kuppulur** [comment]
> Just judging from that one example, it is doing a pretty good job identifying params and vars (even thought this text is different than nl4opt competition data)

+1 to the hybrid nature of our model, which helped us generalize well!

**Comment by kostis-init** [comment]
Thank you for addressing the issue!
